hibernate.connection.url=jdbc:mysql://localhost:3306/rpg
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

hibernate.connection.username=${DB_USERNAME}
hibernate.connection.password=${DB_PASSWORD}


hibernate.connection.autocommit=false
# hibernate.hbm2ddl=validate
hibernate.default.schema=rpg
hibernate.hbm2ddl.auto=update
# hibernate.hbm2ddl.auto=create
# hibernate.generate_statistic=true

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.id.new_generator_mappings=false